# EXPERIMENTAL - NOT expected to be used before fixing
#
# this is an experimental template which uses scaledown controller
# https://github.com/jboss-openshift/statefulset-scaledown-controller
# for the template would be working the controller has to be installed first
# the template does not work properly as the 'postStart' does causes
# the container ends with error exit code and scaledown controller
# repeats in restarting
# the container should be started in suspend mode but it's currently not possible
# and there is a question if suspended container could be shutdown
# https://github.com/jboss-openshift/statefulset-scaledown-controller

---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-eap
    tags: eap,javaee,java,jboss
    version: 1.4.17
    openshift.io/display-name: EAP 7.2 CLUSTER ON STATEFUL SET
    openshift.io/provider-display-name: Red Hat, Inc.
    description: An example Red Hat JBoss EAP 7 application. For more information
      about using this template, see https://github.com/jboss-container-images/jboss-eap-7-openshift-image/blob/eap72/README.adoc
    template.openshift.io/long-description: This template defines resources needed
      to develop a Red Hat JBoss Enterprise Application Platform 7.2 based application,
      including a build configuration, application deployment configuration.
    template.openshift.io/documentation-url: https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/
    template.openshift.io/support-url: https://access.redhat.com
  name: eap72-stateful-set
labels:
  template: eap72-stateful-set
  xpaas: 1.4.17
message: A new EAP 7 based application has been created in your project.
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: ''
  required: true
- displayName: Custom http Route Hostname
  description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
  value: ''
  required: false
- displayName: Git Repository URL
  description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/tadamski/openshift-tx.git
  required: true
- displayName: Git Reference
  description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
  required: false
- displayName: Context Directory
  description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  value: ''
  required: false
- displayName: Queues
  description: Queue names, separated by commas. These queues will be automatically
    created when the broker starts. Also, they will be made accessible as JNDI resources
    in EAP. Note that all queues used by the application *must* be specified here
    in order to be created automatically on the remote AMQ broker.
  name: MQ_QUEUES
  value: ''
  required: false
- displayName: Topics
  description: Topic names, separated by commas. These topics will be automatically
    created when the broker starts. Also, they will be made accessible as JNDI resources
    in EAP. Note that all topics used by the application *must* be specified here
    in order to be created automatically on the remote AMQ broker.
  name: MQ_TOPICS
  value: ''
  required: false
- displayName: AMQ cluster password
  description: AMQ cluster admin password
  name: MQ_CLUSTER_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- displayName: Github Webhook Secret
  description: GitHub trigger secret
  name: GITHUB_WEBHOOK_SECRET
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- displayName: Generic Webhook Secret
  description: Generic build trigger secret
  name: GENERIC_WEBHOOK_SECRET
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you have installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: eap-transactions
  required: true
- displayName: JGroups Cluster Password
  description: JGroups cluster password
  name: JGROUPS_CLUSTER_PASSWORD
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- displayName: Deploy Exploded Archives
  description: Controls whether exploded deployment content should be automatically
    deployed
  name: AUTO_DEPLOY_EXPLODED
  value: 'false'
  required: false
- displayName: Maven mirror URL
  description: Maven mirror to use for S2I builds
  name: MAVEN_MIRROR_URL
  value: ''
  required: false
- displayName: Maven Additional Arguments
  description: Maven additional arguments to use for S2I builds
  name: MAVEN_ARGS_APPEND
  value: "-Dcom.redhat.xpaas.repo.jbossorg"
  required: false
- description: List of directories from which archives will be copied into the deployment
    folder. If unspecified, all archives in /target will be copied.
  name: ARTIFACT_DIR
  value: ''
  required: false
- description: Container memory limit
  name: MEMORY_LIMIT
  value: 1Gi
  required: false
- displayName: Replicas
  description: Number of replicas.
  name: REPLICAS
  value: '1'
  required: true
- displayName: Debug JBoss EAP
  description: Starting JBoss EAP instance with debug port 8787 opened
  name: DEBUG
  value: 'true'
  required: false
- displayName: tx-server host
  description: Name of the tx-server application for the tx-client knowing where to
    connect to with the remote call. This parameter is necessary only for the tx-client.
  name: TX_SERVER_HOST
  value: tx-server
  required: true
- displayName: Debug scripts printing
  description: Running OpenShift EAP scripts with set -x. Set to 'true' to get verbose
    output from the scripts.
  name: SCRIPT_DEBUG
  value: 'false'
  required: false
objects:
  - kind: Service
    apiVersion: v1
    spec:
      clusterIP: None
      ports:
      - port: 8080
        targetPort: 8080
      selector:
        app: "${APPLICATION_NAME}"
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
      annotations:
        description: The web server http port.

  - kind: Service
    apiVersion: v1
    spec:
      publishNotReadyAddresses: true
      clusterIP: None
      ports:
      - name: ping
        port: 8888
      selector:
        app: "${APPLICATION_NAME}"
    metadata:
      name: "${APPLICATION_NAME}-ping"
      labels:
        app: "${APPLICATION_NAME}"
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
        description: The JGroups ping port for clustering.

  - kind: Route
    apiVersion: v1
    id: "${APPLICATION_NAME}-http"
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
      annotations:
        description: Route for application http service.
    spec:
      host: "${HOSTNAME_HTTP}"
      to:
        name: "${APPLICATION_NAME}"

  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: MAVEN_MIRROR_URL
              value: "${MAVEN_MIRROR_URL}"
            - name: MAVEN_ARGS_APPEND
              value: "${MAVEN_ARGS_APPEND}"
            - name: ARTIFACT_DIR
              value: "${ARTIFACT_DIR}"
          forcePull: true
          incremental: true
          from:
            kind: ImageStreamTag
            namespace: "${IMAGE_STREAM_NAMESPACE}"
            name: jboss-eap72-openshift:latest
      output:
        to:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}:latest"
      triggers:
        - type: GitHub
          github:
            secret: "${GITHUB_WEBHOOK_SECRET}"
        - type: Generic
          generic:
            secret: "${GENERIC_WEBHOOK_SECRET}"
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange

  - kind: StatefulSet
    apiVersion: apps/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
        statefulsets.kubernetes.io/scaledown-pod-template: |
          {
            "metadata": {
              "labels": {
                "app": "${APPLICATION_NAME}-scaledown-handler" 
              }
            },
            "spec": {
              "terminationGracePeriodSeconds": 5,
              "containers": [
                {
                  "name": "${APPLICATION_NAME}-scaledown-handler",
                  "image": "172.30.1.1:5000/${IMAGE_STREAM_NAMESPACE}/${APPLICATION_NAME}:latest",
                  "ports": [
                      {
                          "name": "http",
                          "containerPort": 8080,
                          "protocol": "TCP"
                      }
                  ],
                  "lifecycle": {
                      "postStart": {
                          "exec": {
                              "command": [
                                  "/bin/bash",
                                  "-c",
                                  "set -x; while [ `find /opt/eap/standalone/data/tx-object-store -type f | wc -l` -gt 0 ]; do java -cp /opt/eap/modules/system/layers/base/org/jboss/jts/main/narayana-jts-idlj-*.jar com.arjuna.ats.arjuna.tools.RecoveryMonitor -host localhost -port 4712; sleep 10; done; until /opt/eap/bin/jboss-cli.sh -c --command=':read-attribute(name=server-state)'; do echo 'waiting for start...'; sleep 1; done; /opt/eap/bin/jboss-cli.sh -c --command='/subsystem=ejb3:write-attribute(name=enable-graceful-txn-shutdown, value=true)' > /tmp/state;"
                              ]
                          }
                      }
                  },
                  "env": [
                      {
                          "name": "MQ_CLUSTER_PASSWORD",
                          "value": "${MQ_CLUSTER_PASSWORD}"
                      },
                      {
                          "name": "MQ_QUEUES",
                          "value": "${MQ_QUEUES}"
                      },
                      {
                          "name": "MQ_TOPICS",
                          "value": "${MQ_TOPICS}"
                      },
                      {
                          "name": "JGROUPS_CLUSTER_PASSWORD",
                          "value": "${JGROUPS_CLUSTER_PASSWORD}"
                      },
                      {
                          "name": "AUTO_DEPLOY_EXPLODED",
                          "value": "${AUTO_DEPLOY_EXPLODED}"
                      },
                      {
                          "name": "DEBUG",
                          "value": "${DEBUG}"
                      },
                      {
                          "name": "JAVA_OPTS_APPEND",
                          "value": "-Dwildfly.config.url=${JBOSS_HOME}/standalone/configuration/custom-config.xml -Dtx.server.host=${TX_SERVER_HOST}"
                      },
                      {
                          "name": "JAVA_PROXY_OPTIONS",
                          "value": "--start-mode=suspend"
                      },
                      {
                          "name": "SCRIPT_DEBUG",
                          "value": "${SCRIPT_DEBUG}"
                      },
                      {
                          "name": "CLI_GRACEFUL_SHUTDOWN",
                          "value": "true"
                      }
                  ],
                  "volumeMounts": [
                    {
                      "name": "eapdata",
                      "mountPath": "/opt/eap/standalone/data"
                    }
                  ]
                }
              ]  
            } 
          }
    spec:
      serviceName: "${APPLICATION_NAME}"
      replicas: "${REPLICAS}"
      selector:
        matchLabels:
          app: "${APPLICATION_NAME}"
      template:
        metadata:
          name: "${APPLICATION_NAME}"
          labels:
            app: "${APPLICATION_NAME}"
        spec:
          terminationGracePeriodSeconds: 75
          containers:
            - name: "${APPLICATION_NAME}"
              image: 172.30.1.1:5000/${IMAGE_STREAM_NAMESPACE}/${APPLICATION_NAME}:latest
              imagePullPolicy: Always
              resources:
                limits:
                  memory: "${MEMORY_LIMIT}"
              lifecycle:
                postStart:
                  exec:
                    command:
                    - "/bin/bash"
                    - "-c"
                    - | 
                      set -x
                      if [ -f /opt/eap/standalone/configuration/wfly-init.script ]; then
                        COUNT=0
                        until /opt/eap/bin/jboss-cli.sh -c --command=':read-attribute(name=server-state)' | grep -q -E 'result.*running' || [ $COUNT -gt 20 ]; do
                          echo 'waiting for wfly to be started...'
                          COUNT=$((COUNT+1))
                        done
                        /opt/eap/bin/jboss-cli.sh -c --file=/opt/eap/standalone/configuration/wfly-init.script
                      fi 2>&1 > /tmp/PostStart-kubernetes-hook.log
              livenessProbe:
                exec:
                  command:
                  - "/bin/bash"
                  - "-c"
                  - "/opt/eap/bin/livenessProbe.sh"
                initialDelaySeconds: 60
              readinessProbe:
                exec:
                  command:
                  - "/bin/bash"
                  - "-c"
                  - "/opt/eap/bin/readinessProbe.sh"
              ports:
                - name: jolokia
                  containerPort: 8778
                  protocol: TCP
                - name: http
                  containerPort: 8080
                  protocol: TCP
                - name: ping
                  containerPort: 8888
                  protocol: TCP
              env:
                - name: JGROUPS_PING_PROTOCOL
                  value: dns.DNS_PING
                - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                  value: "${APPLICATION_NAME}-ping"
                - name: OPENSHIFT_DNS_PING_SERVICE_PORT
                  value: '8888'
                - name: MQ_CLUSTER_PASSWORD
                  value: "${MQ_CLUSTER_PASSWORD}"
                - name: MQ_QUEUES
                  value: "${MQ_QUEUES}"
                - name: MQ_TOPICS
                  value: "${MQ_TOPICS}"
                - name: JGROUPS_CLUSTER_PASSWORD
                  value: "${JGROUPS_CLUSTER_PASSWORD}"
                - name: AUTO_DEPLOY_EXPLODED
                  value: "${AUTO_DEPLOY_EXPLODED}"
                - name: DEBUG
                  value: "${DEBUG}"
                - name: JAVA_OPTS_APPEND
                  value: "-Dwildfly.config.url=${JBOSS_HOME}/standalone/configuration/custom-config.xml
                    -Dtx.server.host=${TX_SERVER_HOST}"
                - name: SCRIPT_DEBUG
                  value: "${SCRIPT_DEBUG}"
              volumeMounts:
                - name: eapdata
                  mountPath: "/opt/eap/standalone/data"
      volumeClaimTemplates:
        - metadata:
            name: eapdata
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100M

